import type { Metadata } from "next";
import { ArrowRight, BadgeDollarSign, Building2, ClipboardCheck, Smartphone } from "lucide-react";
import Link from "next/link";

import { GrowthLeadForm } from "@/components/growth-lead-form";
import { GrowthLink } from "@/components/growth-link";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";

export const metadata: Metadata = { title: "Contractor pilot" };

export default function ContractorsPage() {
  return <><SiteHeader /><main><section className="hero"><div className="shell hero-grid"><div><div className="eyebrow"><Building2 size={16} /> Contractor pilot</div><h1>Local jobs. Clear payout. Less phone tag.</h1><p className="hero-copy">Drainly is onboarding a small group of approved septic pumping companies for Johnston and Harnett Counties.</p><div style={{ marginTop: 28, display: "flex", gap: 12, flexWrap: "wrap" }}><GrowthLink className="button button-primary" href="/contractor/onboarding" audience="contractor" placement="contractor_hero">Start contractor profile <ArrowRight size={18} /></GrowthLink><Link className="button button-secondary" href="/contractor">View contractor dashboard</Link></div></div><div className="quote-card"><h2>Pilot participation</h2><p>Drainly operations reviews every company before live dispatch.</p><div className="timeline"><div className="timeline-item"><strong>Company verification</strong>Record business, insurance, and pilot approval details.</div><div className="timeline-item"><strong>Stripe-hosted onboarding</strong>Complete connected-account requirements and payout setup.</div><div className="timeline-item"><strong>Service area + capacity</strong>Choose supported counties, weekdays, urgent availability, and daily job limits.</div><div className="timeline-item"><strong>Controlled dispatch</strong>See payout before accepting; one atomic winner per order.</div></div><GrowthLeadForm leadType="CONTRACTOR_INTEREST" source="CONTRACTOR_PAGE" countyCode="UNKNOWN" title="Not ready to create a profile?" /></div></div></section><section className="section section-white"><div className="shell"><div className="steps"><article className="step-card"><BadgeDollarSign size={28} color="var(--teal)" /><h3>Expected payout first</h3><p>Every offer snapshots contractor gross, marketplace fee, and expected payout before acceptance.</p></article><article className="step-card"><Smartphone size={28} color="var(--teal)" /><h3>Field-ready workflow</h3><p>Accept, start route, mark arrival, upload proof, complete, or report access failure from a phone.</p></article><article className="step-card"><ClipboardCheck size={28} color="var(--teal)" /><h3>Recoverable operations</h3><p>Admin-led exception and reassignment paths preserve event history and payment-generation safety.</p></article></div></div></section></main><SiteFooter /></>;
}
