import { ArrowRight, CalendarCheck2, Camera, CheckCircle2, CreditCard, MapPinned, PhoneOff, ShieldCheck, Truck } from "lucide-react";
import Link from "next/link";

import { GrowthLink } from "@/components/growth-link";
import { QuoteWizard } from "@/components/quote-wizard";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";

export default function Home() {
  return <><SiteHeader /><main><section className="hero"><div className="shell hero-grid"><div><div className="eyebrow"><MapPinned size={16} /> Johnston + Harnett Counties</div><h1>Septic pumping without the phone calls.</h1><p className="hero-copy">Enter your address, see a firm price when local supply is available, choose your date, and let Drainly coordinate with a qualified participating contractor.</p><div className="trust-row"><span className="trust-item"><CheckCircle2 size={17} color="var(--teal)" /> Price before booking</span><span className="trust-item"><ShieldCheck size={17} color="var(--teal)" /> Secure card setup</span><span className="trust-item"><PhoneOff size={17} color="var(--teal)" /> No calling around</span></div></div><QuoteWizard /></div></section>
    <section className="section section-white" id="how-it-works"><div className="shell"><div className="section-heading"><div className="eyebrow">A simpler service day</div><h2>From address to pumped tank in three clear steps.</h2><p>Drainly coordinates the marketplace while participating local septic companies perform the work.</p></div><div className="steps"><article className="step-card"><div className="step-number">1</div><h3>Get a supported quote</h3><p>We validate your location, current contractor capacity, pricing, and payout economics before showing a firm total.</p></article><article className="step-card"><div className="step-number">2</div><h3>Choose access and date</h3><p>Be present or provide unattended access instructions. Your card is saved securely and authorized close to service.</p></article><article className="step-card"><div className="step-number">3</div><h3>Track the job</h3><p>See assignment and arrival updates. Unattended jobs include private completion proof before payment is captured.</p></article></div></div></section>
    <section className="section"><div className="shell"><div className="section-heading"><div className="eyebrow">Local pilot coverage</div><h2>Focused on two North Carolina counties.</h2><p>Starting narrow lets Drainly build reliable contractor relationships and strong operating practices before expanding.</p></div><div className="county-grid"><article className="county-card"><div className="county-top"><span className="eyebrow">Pilot market</span><h3>Johnston County</h3></div><div className="county-body">Smithfield, Clayton, Selma, Benson, Princeton, Kenly, and supported surrounding ZIP codes.<div style={{ marginTop: 12 }}><Link href="/service-area/johnston-county-nc">Johnston County coverage</Link></div></div></article><article className="county-card"><div className="county-top harnett"><span className="eyebrow">Pilot market</span><h3>Harnett County</h3></div><div className="county-body">Lillington, Dunn, Angier, Coats, Erwin, Buies Creek, and supported surrounding ZIP codes.<div style={{ marginTop: 12 }}><Link href="/service-area/harnett-county-nc">Harnett County coverage</Link></div></div></article></div></div></section>
    <section className="section section-white"><div className="shell"><div className="callout"><div><h2>Run a local septic company?</h2><p>Drainly gives approved pilot contractors clear offers, expected payout before acceptance, practical job details, and a mobile workflow for service updates and proof.</p></div><GrowthLink href="/contractors" className="button button-primary" audience="contractor" placement="home_contractor">Contractor pilot <ArrowRight size={18} /></GrowthLink></div></div></section>
    <section className="section"><div className="shell"><div className="section-heading"><div className="eyebrow">Built for trust</div><h2>A marketplace flow designed around real service work.</h2></div><div className="steps"><article className="step-card"><CreditCard size={27} color="var(--teal)" /><h3>Safer payment timing</h3><p>Card details stay with Stripe. Drainly authorizes near service and captures after valid completion.</p></article><article className="step-card"><Truck size={27} color="var(--teal)" /><h3>One assigned contractor</h3><p>Database-enforced acceptance ensures two contractors cannot both win the same job.</p></article><article className="step-card"><Camera size={27} color="var(--teal)" /><h3>Private completion proof</h3><p>Unattended photos are stored privately and visible only to the customer, assigned company, and Drainly operations.</p></article></div><div style={{ marginTop: 26, display: "flex", gap: 14, flexWrap: "wrap" }}><Link className="button button-primary" href="#get-a-quote"><CalendarCheck2 size={18} /> Check your address</Link></div></div></section>
  </main><SiteFooter /></>;
}
