"use client";

import { Elements, PaymentElement, useElements, useStripe } from "@stripe/react-stripe-js";
import { loadStripe } from "@stripe/stripe-js";
import { CheckCircle2, CreditCard, LoaderCircle, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";

type Setup = { customerId: string; setupIntentId: string; clientSecret: string; paymentMethodId?: string };

function idempotencyKey(prefix: string) { return `${prefix}-${crypto.randomUUID()}`; }

function SetupPaymentForm({ quoteId, setup, onComplete }: { quoteId: string; setup: Setup; onComplete: (order: Record<string, unknown>) => void }) {
  const stripe = useStripe(); const elements = useElements(); const [loading, setLoading] = useState(false); const [error, setError] = useState<string>();
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!stripe || !elements) return; setLoading(true); setError(undefined); const confirmation = await stripe.confirmSetup({ elements, redirect: "if_required" }); if (confirmation.error) { setLoading(false); return setError(confirmation.error.message); } const paymentMethod = typeof confirmation.setupIntent?.payment_method === "string" ? confirmation.setupIntent.payment_method : confirmation.setupIntent?.payment_method?.id; if (!paymentMethod) { setLoading(false); return setError("Stripe did not return a reusable payment method."); } const response = await fetch("/api/bookings", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": idempotencyKey("booking") }, body: JSON.stringify({ quoteId, stripeCustomerId: setup.customerId, setupIntentId: setup.setupIntentId, paymentMethodId: paymentMethod, offSessionConsentAccepted: true, consentVersion: "pilot-v1" }) }); const data = await response.json() as Record<string, unknown> & { error?: { message?: string } }; setLoading(false); if (!response.ok) return setError(data.error?.message ?? "Booking failed"); onComplete(data); }
  return <form className="stack" onSubmit={submit}><PaymentElement options={{ layout: "tabs" }} />{error && <div className="form-error" role="alert">{error}</div>}<button className="button button-primary" disabled={!stripe || loading}>{loading ? <><LoaderCircle size={18} className="animate-spin" /> Saving and booking…</> : <><CreditCard size={18} /> Save card and submit booking</>}</button></form>;
}

export function BookingCheckout({ quoteId, email }: { quoteId: string; email: string }) {
  const publishableKey = process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY;
  const stripePromise = useMemo(() => publishableKey ? loadStripe(publishableKey) : null, [publishableKey]);
  const [consent, setConsent] = useState(false); const [setup, setSetup] = useState<Setup>(); const [order, setOrder] = useState<Record<string, unknown>>(); const [loading, setLoading] = useState(false); const [error, setError] = useState<string>();
  async function prepare() { setLoading(true); setError(undefined); const response = await fetch("/api/payments/setup-intent", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": idempotencyKey("setup") }, body: JSON.stringify({ email }) }); const data = await response.json() as Setup & { error?: { message?: string } }; setLoading(false); if (!response.ok) return setError(data.error?.message ?? "Payment setup failed"); setSetup(data); if (!stripePromise && data.paymentMethodId) { const booking = await fetch("/api/bookings", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": idempotencyKey("booking") }, body: JSON.stringify({ quoteId, stripeCustomerId: data.customerId, setupIntentId: data.setupIntentId, paymentMethodId: data.paymentMethodId, offSessionConsentAccepted: true, consentVersion: "pilot-v1" }) }); const bookingData = await booking.json() as Record<string, unknown> & { error?: { message?: string } }; if (!booking.ok) return setError(bookingData.error?.message ?? "Booking failed"); setOrder(bookingData); } }
  if (order) return <div className="success-box"><CheckCircle2 size={20} style={{ display: "inline", marginRight: 8 }} /><strong>Your price is locked.</strong><p>We&apos;re confirming a local service provider for your requested date. Your service date is confirmed once a local contractor accepts the job. Reference: {String(order.publicRef ?? order.orderId ?? "pending")}</p></div>;
  return <div className="stack"><div className="panel"><div className="panel-header"><h2>Payment method</h2><ShieldCheck size={20} color="var(--teal)" /></div><div className="panel-body stack"><p style={{ margin: 0, color: "var(--muted)" }}>Drainly saves your card with Stripe. Scheduled jobs are authorized close to service and captured only after valid completion.</p><label style={{ display: "flex", gap: 10, alignItems: "flex-start", fontSize: ".88rem" }}><input type="checkbox" checked={consent} onChange={(e) => setConsent(e.target.checked)} style={{ marginTop: 4 }} /><span>I authorize Drainly to save this payment method and initiate one off-session charge for the displayed booking total after the authorization and completion conditions described above.</span></label>{error && <div className="form-error" role="alert">{error}</div>}{!setup && <button className="button button-primary" disabled={!consent || loading} onClick={prepare}>{loading ? <LoaderCircle size={18} className="animate-spin" /> : <><CreditCard size={18} /> Continue to secure card setup</>}</button>}{setup && stripePromise && <Elements stripe={stripePromise} options={{ clientSecret: setup.clientSecret, appearance: { theme: "stripe", variables: { colorPrimary: "#0d6b63", borderRadius: "12px" } } }}><SetupPaymentForm quoteId={quoteId} setup={setup} onComplete={setOrder} /></Elements>}</div></div></div>;
}
